### ISSUE TITLE
是否只支持iOS9.0及以上系统？

### ISSUE THREAD

**Issue by coderxdotwang** [GLChan/ZAKER-C#46]
我看了一下源码，首页的collectionView用到了iOS9.0以后新增的方法，不知道是否有考虑支持低版本

**Comment by GLChan** [comment]
呵呵, 暂时没有的, 这个只是一个业余项目, 最近也很忙. 没时间弄😂

**Comment by coderxdotwang** [comment]
噢，最近在做类似于ZAKER的首页模块拖动，支持低版本似乎要花点功夫

**Comment by GLChan** [comment]
网上应该有很多相关源码, 你可以找找看

**Comment by coderxdotwang** [comment]
嗯，找到了一个：[RACollectionViewReorderableTripletLayout](https://github.com/ra1028/RACollectionViewReorderableTripletLayout)
